DROP TABLE a2;

CREATE TABLE a2 (
    id int,
    wert1 int,
    wert2 int
);

INSERT ALL
   INTO a2 VALUES (1, 3, 2)
   INTO a2 VALUES (2, 5, 8)
   INTO a2 VALUES (3, 4, 10)
   INTO a2 VALUES (4, 1, 1)
   INTO a2 VALUES (5, 2, 8)
   INTO a2 VALUES (6, 5, 4)
   INTO a2 VALUES (7, 4, 9)
   INTO a2 VALUES (8, 4, 9)
   INTO a2 VALUES (9, 4, 6)
   INTO a2 VALUES (10, 2, 8)
SELECT 1 FROM DUAL;

SELECT id, wert1, wert2, 
ROW_NUMBER() OVER (ORDER BY WERT1) as a, 
RANK() OVER (ORDER BY WERT1) as b, 
DENSE_RANK() OVER (ORDER BY WERT1) as c,
ROW_NUMBER() OVER (PARTITION BY WERT1 ORDER BY WERT2) as d,
RANK() OVER (PARTITION BY WERT1 ORDER BY WERT2) as e, 
DENSE_RANK() OVER (PARTITION BY WERT1 ORDER BY WERT2) as f, 
SUM(WERT2) OVER (PARTITION BY WERT1) as g, 
SUM(WERT2) OVER (PARTITION BY WERT1 ORDER BY ID) as h
FROM a2;